[package]
name = "spel-right"
description = "A fast and lightweight spell checker and suggester."
version = "0.6.0"
edition = "2024"
license-file = "LICENSE"
repository = "https://github.com/Zefirchiky/SpelRight"

[dependencies]
directories = "6.0.0"
filess = { version = "0.9.0", default-features = false, features = ["dirs", "json", "txt"] }
rayon = "1.12.0"
serde = { version = "1.0.229", features = ["serde_derive"] }
unicode-normalization = "0.1.25"

[profile.dev]
incremental = true

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
# panic = "abort"
# strip = true

[dev-dependencies]
criterion = "0.7.0"
pretty_assertions = { version = "1.4.1", features = ["unstable"] }
